### ISSUE TITLE
Fault at starting

### ISSUE THREAD

**Issue by MarkusHackspacher** [itsthejoker/Pokemon-Homage#1]
```
$ python pokemon_python.py 
{'splash1': <Surface(800x600x32 SW)>}
Traceback (most recent call last):
  File "pokemon_python.py", line 14, in <module>
    main()
  File ".../Pokemon-Homage/data/main.py", line 18, in main
    "OVERWORLD"   : game.Game(), # wandering around
NameError: global name 'game' is not defined
```

**Comment by itsthejoker** [comment]
This project is nowhere near done or even runnable. Thanks for trying, though!
